//! Heap stores the runtime variables
pub mod access_flags;
pub mod array_class;
pub mod array_object;
pub mod class;
pub mod class_loader;
pub mod class_name_helper;
pub mod class_ref;
pub mod constant;
pub mod consts;
pub mod errors;
mod exception_table;
pub mod field;
pub mod field_ref;
pub mod interface_ref;
pub mod method;
pub mod method_descriptor;
pub mod method_lookup;
pub mod method_ref;
pub mod object_clone;
pub mod object_ref;
pub mod runtime_constant_pool;
pub mod string_pool;
